name: deploy test
on:
  push:
    branches:
      - master
jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: ssh command
        uses: D3rHase/ssh-command-action@v0.2
          with:
            HOST: ${{secrets.HOST}}
            USER: ${{secrets.USER}}
            PRIVATE_SSH_KEY: ${{secrets.PRIVATE_SSH_KEY}}
            COMMAND: ${{secrets.COMMAND}}
      - name: command
        run: ll