name: deploy test
on:
  push:
    branches:
      - master
jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: ssh
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.HOST }}
