name: deploy test
on:
  push:
    branches:
      - master
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2
      - name: Check Node v
        run: node -v
      uses: D3rHase/ssh-command-action@v0.2
        with:
          HOST: ${{secrets.HOST}}
          USER: ${{secrets.USER}}
          PRIVATE_SSH_KEY: ${{secrets.PRIVATE_SSH_KEY}}
          COMMAND: ${{secrets.COMMAND}}
