name: deploy test
on:
  push:
    branches:
      - master
jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            ll
          host: ${{ secrets.HOST }}
          user: ${{secrets.USER}}
          key: ${{ secrets.PRIVATE_KEY}}
