name: deploy test

on:
  push:
    - master

jobs:
  build-app:
    step:
      # - uses: actions/checkout@v2
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: '16.x'
      - uses: D3rHase/ssh-command-action@{version}
        with:
          HOST: ${{secrets.HOST}}
          USER: ${{secrets.USER}}
          PRIVATE_SSH_KEY: ${{secrets.PRIVATE_SSH_KEY}}
          COMMAND: ${{secrets.COMMAND}}
